# Generated by Django 6.1.1 on 2026-09-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], max_length=20),
        ),
    ]
