# Generated by Django 6.1.1 on 2026-09-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='properties.rentalapplication'),
        ),
    ]
