# Generated by Django 6.1.1 on 2026-09-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_lease_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='properties.rentalapplication'),
        ),
    ]
