# Generated by Django 6.1.1 on 2026-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
